settings:
  title: 'gk.wtf Statis'
  url: 'https://status.gk.wtf' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: alldeals # unique identifier
    name: deals.gk.wtf
    description: 'AllDeals instance.' # default=empty
    url: 'https://deals.gk.wtf' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: gianklug
    name: gianklug.com
    description: 'Main Website'
    url: 'https://gianklug.com'
    method: GET
    expectStatus: 200

  - id: ott
    name: yt.gk.wtf
    description: 'OpenTogetherTube'
    url: 'https://yt.gk.wtf'
    method: GET
    expectStatus: 200
